language: php

php:
  - '5.5'

matrix:
  fast_finish: true
  include:
    - php: 5.5

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script:
  - phpunit

notifications:
  email: webmaster@esnlille.fr