language: php

php:
  - '5.5'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate

install: composer install

script:
  - phpunit

notifications:
  email: webmaster@esnlille.fr