language: php

php:
  - '5.6'

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit

notifications:
  email:
    recipients:
      - jeremie.samson@ix.esnlille.fr
    on_success: [never]
    on_failure: [always]
