version: "3.2"

networks:
    erp:
        external:
            name: erp

services:
    app:
        networks:
            erp:
                aliases:
                  - erp.code
        volumes:
            - "~/.composer:/root/.composer"
        environment:
            - VIRTUAL_HOST=erp.code
        ports:
          - 8000:80

    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        networks:
            - default
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
            VIRTUAL_HOST: phpmyadmin.erp.code

    db:
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: erp
