version: "3.2"

services:
    app:
        networks:
            default:
                aliases:
                    - erp.code
        build: docker/dev
        depends_on:
            - db
        volumes:
            - .:/app

    db:
        image: mysql:5.7.14
        volumes:
            - ./docker/dev/my.cnf:/etc/mysql/conf.d/my.cnf
