#version: '3.2'

#networks:
#  erp:
#    external:
#      name: erp

#services:
#  apache:
#    build: .docker/apache
#    container_name: erp4_apache
#    depends_on:
#      - app
#    volumes:
#      - .docker/config/vhosts:/etc/apache2/sites-enabled
#      - .:/var/www/erp
#    networks:
#      - erp
#    ports:
#      - 8000:80

#  app:
#    build: .docker/app
#    container_name: erp4_app
#    volumes:
#      - .:/var/www/erp
#    depends_on:
#      - mysql
#    networks:
#      - erp

#  mysql:
#    image: mysql:5.7
#    container_name: erp4_mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - 3306:3306
#    volumes:
#      - .docker/data/db:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: erp
#    networks:
#      - erp

#  maildev:
#    image: djfarrelly/maildev
#    container_name: erp4_maildev
#    ports:
#      - 8001:80

#  pma:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - mysql
#    networks:
#      - erp
#    ports:
#      - "8080:80"
#    environment:
#      PMA_HOST: mysql
#      PMA_USER: root
#      PMA_PASSWORD: root
#      VIRTUAL_HOST: phpmyadmin.erp.code
