esn_members_homepage:
    path:     /members/{type}
    defaults: { _controller: ESNMembersBundle:Members:index, action:"lister" }
    
esn_members_detail:
    path:     /members/{type}/{id}
    defaults: {  _controller: ESNMembersBundle:Members:index, action:"detailler" }
    requirements:
        id:  \d+
        
esn_members_edit:
    path:     /members/{type}/{id}/edit
    defaults: {  _controller: ESNMembersBundle:Members:index, action:"editer" }
    requirements:
        id:  \d+
        
esn_members_erasmus_delete:
    path: /members/erasmus/{id}/delete
    defaults: { _controller: ESNMembersBundle:Members:delete }
    requirements:
        id: \d+