esn_members_homepage_esners:
    path:     /members/esners
    defaults: { _controller: ESNMembersBundle:Members:listEsner }

esn_members_homepage:
    path:     /members/{type}
    defaults: { _controller: ESNMembersBundle:Members:index, action:"lister" }
    
esn_members_detail:
    path:     /members/{type}/{id}
    defaults: {  _controller: ESNMembersBundle:Members:index, action:"detailler" }
    requirements:
        id:  \d+

esn_members_erasmus_edit:
    path: /members/erasmus/{id}/edit
    defaults: { _controller: ESNMembersBundle:Members:editErasmus }
    requirements:
            id:  \d+

esn_members_esner_edit:
    path:     /members/esners/{user_id}/edit
    defaults: {  _controller: ESNMembersBundle:Members:editEsner }
    requirements:
        user_id:  \d+
        
esn_members_erasmus_create:
    path: /members/erasmus/create
    defaults: { _controller: ESNMembersBundle:Members:createErasmus }



esn_members_erasmus_delete:
    path: /members/erasmus/{id}/delete
    defaults: { _controller: ESNMembersBundle:Members:delete }
    requirements:
        id: \d+


        
