esn_user:
    resource: "@ESNUserBundle/Resources/config/routing.yml"
    prefix:   /

esn_admin:
    resource: "@ESNAdminBundle/Resources/config/routing.yml"
    prefix:   /
    
esn_login:
    resource: "@ESNLoginBundle/Resources/config/routing.yml"
    prefix:   /

