esn_user:
    resource: "@ESNUserBundle/Resources/config/routing.yml"
    prefix:   /

esn_dashboard:
    resource: "@ESNDashboardBundle/Resources/config/routing.yml"
    prefix:   /
    
esn_login:
    resource: "@ESNLoginBundle/Resources/config/routing.yml"
    prefix:   /

