esn_hr_association:
    path:     /human-resources/association
    defaults: { _controller: ESNHRBundle:HR:index, type:"association" }
    
esn_hr_recruitment:
    path:     /human-resources/recruitment
    defaults: { _controller: ESNHRBundle:HR:index, type:"recruitment" }