esn_hr_association:
    path:     /human-ressources/association
    defaults: { _controller: ESNHRBundle:Association:index}
    
esn_hr_association_add:
    path:   /human-ressources/association/add
    defaults: { _controller: ESNHRBundle:Association:newESNer}

esn_hr_association_delete:
    path:   /human-ressources/association/delete/{id}
    defaults: { _controller: ESNHRBundle:Association:deleteESNer}
    
esn_hr_association_edit:
    path:   /human-ressources/association/edit/{id}
    defaults: { _controller: ESNHRBundle:Association:editESNer}    

################## TREECERATOPS ########################

esn_hr_treeceratops:
    path:   /human-ressources/treeceratops
    defaults: { _controller : ESNHRBundle:HR:treeceratops}

################## RECRUITMENT ########################

esn_hr_recruitment_create:
    path:   /human-ressources/recruitment/create
    defaults: { _controller : ESNHRBundle:Recruitment:createApply}

esn_hr_recruitment_create_short:
    path:   /postuler
    defaults: { _controller : ESNHRBundle:Recruitment:createApply}

esn_hr_recruitment_add_recruiter:
    path:   /human-ressources/recruitment/recruiter/add
    defaults: { _controller : ESNHRBundle:Recruitment:addRecruiter}

esn_hr_recruitment_view:
    path:   /human-ressources/recruitment/view/{apply_id}
    defaults: { _controller : ESNHRBundle:Recruitment:viewApply}
    requirements:
        apply_id:  \d+

esn_hr_recruitment_delete:
    path:   /human-ressources/recruitment/delete/{apply_id}
    defaults: { _controller : ESNHRBundle:Recruitment:deleteApply}
    requirements:
        apply_id:  \d+

esn_hr_recruitment:
    path:   /human-ressources/recruitment
    defaults: { _controller : ESNHRBundle:Recruitment:list}
