esn_permanence_trips:
    path:     /permanence/trips
    defaults: { _controller: ESNPermanenceBundle:Permanence:index, type:"trips" }
    
esn_permanence_seeTrip:
    path:     /permanence/trip/{id}
    defaults: { _controller: ESNPermanenceBundle:Permanence:detailTrips, type:"trips" }
    
esn_permanence_enrollUserToTrip:
    path:     /permanence/enrollUserToTrip/
    defaults: { _controller: ESNPermanenceBundle:Permanence:enrollUserToTrip, type:"trips" }

esn_permanence_reports:
    path:     /permanence/reports
    defaults: { _controller: ESNPermanenceBundle:Permanence:index, type:"reports"}
    
esn_permanence_seeReport:
    path:     /permanence/seeReport/{id}
    defaults: { _controller: ESNPermanenceBundle:Permanence:seeReport, type:"reports"}

esn_permanence_createReports:
    path:     /permanence/createReports
    defaults: { _controller: ESNPermanenceBundle:Permanence:createReport, type:"reports"}
    
esn_permanence_informations:
    path:     /permanence/informations
    defaults: { _controller: ESNPermanenceBundle:Permanence:index, type:"informations" }
    
