############################# TRIPS ################################################
esn_permanence_trips:
    path:     /permanence/trips
    defaults: { _controller: ESNPermanenceBundle:Permanence:listTrips }
    
esn_permanence_seeTrip:
    path:     /permanence/trip/{id}
    defaults: { _controller: ESNPermanenceBundle:Permanence:detailTrips }
    
esn_permanence_enrollUserToTrip:
    path:     /permanence/enrollUserToTrip/
    defaults: { _controller: ESNPermanenceBundle:Permanence:enrollUserToTrip }

esn_permanence_removeTripUser:
    path:     /permanence/trip/{trip_id}/user/{user_id}/delete
    defaults: { _controller: ESNPermanenceBundle:Permanence:removeUserToTrip }

############################## REPORTS ##############################################

esn_permanence_reports:
    path:     /permanence/reports
    defaults: { _controller: ESNPermanenceBundle:Permanence:listReports}
    
esn_permanence_seeReport:
    path:     /permanence/seeReport/{id}
    defaults: { _controller: ESNPermanenceBundle:Permanence:seeReport}

esn_permanence_createReports:
    path:     /permanence/createReports
    defaults: { _controller: ESNPermanenceBundle:Permanence:create}
    
esn_permanence_informations:
    path:     /permanence/informations
    defaults: { _controller: ESNPermanenceBundle:Permanence:index }
    
