<?php

namespace ESN\HRBundle\Entity;

/**
 * EsnerFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EsnerFollowRepository extends \Doctrine\ORM\EntityRepository
{
}
