<?php

namespace ESN\MembersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EsnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EsnerRepository extends EntityRepository
{
}
